# Generated by Django 2.0.6 on 2021-08-26 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('pk_client', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='nombre')),
                ('telefono', models.CharField(max_length=8, verbose_name='nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pk_product', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='precio')),
                ('discount', models.IntegerField(default=0, verbose_name='descuento')),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('pk_purchase', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('amount', models.IntegerField(verbose_name='cantidad')),
                ('date_purchase', models.DateField(auto_now_add=True, verbose_name='fecha compra')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.product')),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('pk_sale', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('amount', models.IntegerField(verbose_name='cantidad')),
                ('state', models.BooleanField(default=True, verbose_name='cantidad')),
                ('fk_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.client')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.product')),
            ],
        ),
    ]
